// AUTO-GENERATED by scripts/generate-build-info.js — do not edit by hand.
// Regenerated on every build via the npm prebuild/pretest hook. The value
// checked into git is only the fallback used when this script hasn't run
// (see script header comment for why it exists and how it's wired in).
export const BUILD_STAMP = 'dev';
